import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WagmiProvider } from "./wagmi-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Jungle Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
=======
<<<<<<< HEAD
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
=======
      <body className={`${geistSans.variable}`}>
        <WagmiProvider>{children} </WagmiProvider>
>>>>>>> 38e672f66aeb9f9cff54258830ad7d5cb8058f8b
>>>>>>> b7d43f0e09131914f16a66d9936907dbf1e27814
      </body>
    </html>
  );
}
